from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi


def remove_body_schemas(app: FastAPI) -> None:
    """
    Removes automatically generated schemas for endpoints that accept form encoded data.
    This solution is inspired by https://github.com/tiangolo/fastapi/issues/1442.

    The main reason one might want to do this is to clean up the OpenAPI schema
    generated by FastAPI because by default the auto-generated schemas are named
    Body_<function>_<path>_<method> which is inconsistent to other schemas.
    """

    def custom_openapi():
        if app.openapi_schema:
            return app.openapi_schema
        openapi_schema = get_openapi(
            title=app.title,
            version=app.version,
            openapi_version=app.openapi_version,
            description=app.description,
            routes=app.routes,
            tags=app.openapi_tags,
            servers=app.servers,
            terms_of_service=app.terms_of_service,
            contact=app.contact,
            license_info=app.license_info,
        )
        # Move autogenerated Body_ schemas.
        # See https://github.com/tiangolo/fastapi/issues/1442
        for path in openapi_schema["paths"].values():
            for method_data in path.values():
                if "requestBody" in method_data:
                    for content_type, content in method_data["requestBody"][
                        "content"
                    ].items():
                        if content_type in [
                            "multipart/form-data",
                            "application/x-www-form-urlencoded",
                        ]:
                            schema_name = content["schema"]["$ref"].lstrip(
                                "#/components/schemas/"
                            )
                            schema_data = openapi_schema["components"]["schemas"].pop(
                                schema_name
                            )
                            content["schema"] = schema_data
        app.openapi_schema = openapi_schema
        return app.openapi_schema

    app.openapi = custom_openapi
