# Default Karman Logging Configuration
# Integrates Uvicorn Logs and SQLAlchemy/Alembic Logs
version: 1

formatters:
  default:
    (): "karman.util.logging.ColorFormatter"
    fmt: "%(asctime)s | %(levelname)8s | %(name)s: %(message)s"
    color_fmt: "%(asctime)s | %(levelname)21s | %(name)s %(message)s"
    colors:
      asctime: {dim: true}
      levelname: {level: true, bold: true}
      name: {fg: bright_black, bold: true}
    level_colors:
      50: {fg: bright_red, blink: true}
  access:
    (): "karman.util.logging.AccessFormatter"
    fmt: "%(asctime)s | %(levelname)8s | %(client_addr)s %(method)s %(full_path)s HTTP/%(http_version)s -> %(status_code)s %(status_phrase)s"
    color_fmt: "%(asctime)s | %(levelname)21s | %(client_addr)s %(method)s %(full_path)s HTTP/%(http_version)s -> %(status_code)s %(status_phrase)s"
    colors:
      asctime: {fg: bright_black}
      levelname: { level: true, bold: true }
      client_addr: {dim: true}
      method: {bold: true}
      full_path: {italic: true}
      status_code: {status: true, bold: true}
      status_phrase: {status: true, bold: true}
    level_colors:
      50: { fg: bright_red, blink: true }

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout

loggers:
  karman:
    level: INFO
  karman.api:
    level: NOTSET
  karman.auth:
    level: NOTSET
  uvicorn:
    level: INFO
  uvicorn.access:
    level: INFO
    handlers: ["access"]
    propagate: false
  uvicorn.error:
     level: NOTSET
  sqlalchemy.engine:
    level: WARN
  alembic:
    level: INFO

root:
  level: WARN
  handlers: [default]
