"""empty message

Revision ID: 817ebd4c0189
Revises: 
Create Date: 2020-03-26 00:56:28.359202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817ebd4c0189'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('scope',
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.String(length=94), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('role_scopes',
    sa.Column('role_name', sa.Integer(), nullable=False),
    sa.Column('scope_name', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['role.name'], ),
    sa.ForeignKeyConstraint(['scope_name'], ['scope.name'], ),
    sa.PrimaryKeyConstraint('role_name', 'scope_name')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['role.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_name')
    )
    op.create_table('user_scopes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_name', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scope_name'], ['scope.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'scope_name')
    )
    op.insert_row('scope', **{'name': 'users:manage'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.delete_row('scope', **{'name': 'users:manage'})
    op.drop_table('user_scopes')
    op.drop_table('user_roles')
    op.drop_table('role_scopes')
    op.drop_table('user')
    op.drop_table('scope')
    op.drop_table('role')
    # ### end Alembic commands ###
