"""empty message

Revision ID: be6e5b8cbd58
Revises: 5b747c7d8a9f
Create Date: 2020-03-30 21:21:32.115020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6e5b8cbd58'
down_revision = '5b747c7d8a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('upload')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target', sa.VARCHAR(length=10), nullable=True),
    sa.Column('file', sa.TEXT(), nullable=True),
    sa.CheckConstraint("target IN ('IMPORTS', 'USER_SONGS', 'LIBRARY')", name='type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('import')
    # ### end Alembic commands ###
