"""Add user model

Revision ID: 4795aa8b5e4c
Revises: 91df67611d87
Create Date: 2022-04-19 15:25:26.684863

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4795aa8b5e4c"
down_revision = "91df67611d87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
