"""create song model

Revision ID: 91df67611d87
Revises:
Create Date: 2021-12-27 00:32:24.888557

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91df67611d87"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("songs")
    # ### end Alembic commands ###
